# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiSending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('attempt_time', models.DateTimeField(blank=True, null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('delivered_time', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'api_sending',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='PhoneData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
                ('key', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('backup_phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'phone_data',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='ResourceIdGenerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='security_key_name')),
                ('resource_id', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'resource',
            },
        ),
        migrations.AddField(
            model_name='apisending',
            name='phoneobject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.PhoneData'),
        ),
    ]
