# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonedata',
            name='vicidial_eagent_attempt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phonedata',
            name='vicidial_eagent_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phonedata',
            name='vicidial_tcm_attempt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phonedata',
            name='vicidial_tcm_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phonedata',
            name='xencall_attempt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phonedata',
            name='xencall_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
