# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0002_auto_20171210_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonedata',
            name='vicidial_eagent_attempt',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='phonedata',
            name='vicidial_tcm_attempt',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='phonedata',
            name='xencall_attempt',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
