# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 06:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0002_auto_20171213_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='API_CONFIG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('url', models.TextField(validators=[django.core.validators.URLValidator()])),
            ],
        ),
    ]
