# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0003_auto_20171210_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiSending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('attempt_time', models.DateTimeField(blank=True, null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('delivered_time', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.RemoveField(
            model_name='phonedata',
            name='number_delivered',
        ),
        migrations.RemoveField(
            model_name='phonedata',
            name='vicidial_eagent_attempt',
        ),
        migrations.RemoveField(
            model_name='phonedata',
            name='vicidial_eagent_delivered',
        ),
        migrations.RemoveField(
            model_name='phonedata',
            name='vicidial_tcm_attempt',
        ),
        migrations.RemoveField(
            model_name='phonedata',
            name='vicidial_tcm_delivered',
        ),
        migrations.RemoveField(
            model_name='phonedata',
            name='xencall_attempt',
        ),
        migrations.RemoveField(
            model_name='phonedata',
            name='xencall_delivered',
        ),
        migrations.AddField(
            model_name='apisending',
            name='phoneobject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.PhoneData'),
        ),
    ]
