# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 05:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0004_auto_20171212_1022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apisending',
            options={'ordering': ('created',), 'verbose_name': 'api_sending'},
        ),
        migrations.AlterModelOptions(
            name='phonedata',
            options={'ordering': ('created',), 'verbose_name': 'phone_data'},
        ),
        migrations.AlterModelOptions(
            name='resourceidgenerator',
            options={'verbose_name': 'resource'},
        ),
    ]
